# Example using MS Build of OpenJDK image directly
FROM mcr.microsoft.com/openjdk/11-ubuntu

# Continue with your application deployment
RUN mkdir /opt/app
COPY japp.jar /opt/app
CMD ["java", "-jar", "/opt/app/japp.jar"]
