management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /appdetails
  endpoint:
    health:
      show-components: always
      show-details: always
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
info:
  myapp:
    name: SathishAppForAzure
    version: 1.0.0
    author: dotsky
    website: https://sathishjayapal.me
  app:
    encoding: @project.build.sourceEncoding@
spring:
  jmx:
    enabled: false

